NW6 | Rabia Avci | Full-Stack-Project | Week-2 | Post new video endpoint
RbAvci/Full-Stack-Project-Assessment pull request #24
Opened 2024-05-16 00:21 UTC by RbAvci

Completed these tasks for this ticket:

-  There is a POST /api/videos backend endpoint to facilitate adding videos to the database.
-  The endpoint generates and attaches a unique ID to each newly added video.
-  The endpoint accepts video data in JSON format (example provided).
-  The endpoint responds with a JSON response that includes the generated id (example provided)

2024-05-16 17:23 UTC, zelihapala approved these changes
Well done!

2024-05-16 17:23 UTC, merged

2024-05-17 05:47 UTC, Ara225 requested changes
Overall, this works just fine, but there are some important issues that are worth reviewing. You'll find that as your applications get more complex, there are more of these issues. Embrace them all learn the why, they're intresting and will help you grow your  knowledge

2024-05-17 05:47 UTC, Ara225 commented on db/initdb.sql
> +    id SERIAL PRIMARY KEY,
👍

2024-05-17 05:47 UTC, Ara225 commented on server/api.js
> +		return res.status(422).json({ message: "src field is required" });
It is good to see you using HTTP status codes other than 200 and thinking carefully about the right one to use. However, it's worth being aware that there are conventions - 400 bad request is usually  used for this situation. It makes it very clear that the problem is on the users side.

The message is a nice touch and would be much appreciated when debugging!

2024-05-17 05:47 UTC, Ara225 commented on server/api.js
> +		`INSERT INTO videos (title,src) VALUES ('${req.body.title}','${req.body.src}') RETURNING id`
This line works, but sadly it's  horribly insecure thanks to SQL injection. Anyone could delete your videos table just by sending a src with a value like this:
Fakesrc');DROP TABLE videos;

I don't know if Kieth mentioned this, and even if he did, it's easy not to make the connection so there’s no shame in having made the mistake. However, you need to get into the habit of doing  the right thing have a look at  https://stackoverflow.com/questions/58174695/prevent-sql-injection-with-nodejs-and-postgres

2024-05-17 05:47 UTC, Ara225 commented on server/api.js
> +	res.status(200).json({ success: true, data: { id: newVideoId } });
It's good that you're sending  back the video ID that's  extremely useful 👍

2024-05-17 05:47 UTC, Ara225 commented on server/app.js
> +});
So good to see error handling and the health endpoint but there's a major issue with doing it just in this file. None of the stuff in this file ever runs in Netifly (the starting point for Netlifly is functions/app.mjs), so this code only works on your local machine. If this is intentional, that's  fine, but please add a comment to clarify :)